### PR TITLE
Update Code - Proof_Of_ContributionSnapshot4.md

### PR DESCRIPTION
**Pull request by Terry-50000**

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
1,000 weights seems like a lot for updating a favicon. I'll review.

**Comment by Terry-50000** [comment]
Regarding the weight settings, I'd like to ask if it's possible to label the weight of an issue when it's created, or to dedicate some people to  admin to managing the weights.
And regarding the 1,000weight, its theoretical value may be 250 bucks, I suppose
(In theory, 1MOR = 100$, 1.26$ per weight. It means if 1 MOR = 20$, 0.24$ per weight.)

**Comment by ArtemUpnode** [comment]
Could you resolve the conflict, please.

**Comment by betterbrand** [comment]
still a lot of weights for a favicon.

**Pull request closed without merging**
