### PR TITLE
Add contribution to Proof_Of_ContributionSnapshot5.md

### PR DESCRIPTION
**Pull request by ArtemUpnode**
> [!NOTE]  
> This is a resubmission of this [PR](https://github.com/MorpheusAIs/Docs/pull/233) after new app updates (and exploration) with updated weights:
>  - reduced by 35% based on the new Implied value of a Weight
>  - added 7% for development of v0.1.0 version

Added contribution for [HSM-Agents-Hub](https://github.com/ArtemUpnode/HSM-Agents-Hub).

HSM Agents Hub is a collection of Morpheus smart agents with the ability to connect different HSMs (YubiHSM, Ledger, etc) to manage the device and sign messages and transactions. Built with LangChain.js (ollama, llama3), ai.js, Tauri and Next.js.

preview 1

preview 2

preview 3

### @YubiHSM

Manages the YubiHSM device and signs messages and transactions.

**Available Functionality:**

1. **Get connected YubiHSM user devices to PC**
    - **Description:** Retrieves a list of YubiHSM devices connected to the PC.
    - **Required Parameters:** None
    - **Example:** `@YubiHSM My devices`

2. **Get keys in YubiHSM user device**
    - **Description:** Fetches keys stored in a YubiHSM user device.
    - **Required Parameters:**
      - `device_serial_id`: (string) YubiHSM device serial id
      - `auth_key_id`: (number) YubiHSM auth key id
      - `password`: (string) YubiHSM auth key password
    - **Example:** `@YubiHSM Get keys in device "123456", auth key 1, password "your_password"`

3. **Sign a user message with a specific key in YubiHSM user device**
    - **Description:** Signs a given message using a specific key stored in the YubiHSM user device.
    - **Required Parameters:**
      - `message`: (string) Message for signing
      - `device_serial_id`: (string) YubiHSM device serial id
      - `auth_key_id`: (number) YubiHSM auth key id
      - `password`: (string) YubiHSM auth key password
      - `signing_key_id`: (number) Id of the key that signs the message
    - **Example:** `@YubiHSM Sign message "Hello World" with device "123456", auth key 1, password "your_password" and key id 2`

## Under development/In plans

- Extend the functionality of `list_keys` and `sign_message` by adding support for other chains: Cosmos (secpk256k1) and Solana, Aptos, Sui (Ed25519)
- Functions `generateKeys` for YubiHSM. Discussed need for `importKeys`, `exportKeys` functions (may be unsafe)
- Ledger support
- Integration with web3 provider and sending transactions
- Interface/server improvements
- Fixing known bugs

## Challenges Diary

- To interact with YubiHSM devices from the JS side, a wrapper was developed over the yubihsmrs library in Tauri. Function calls also work in Node.js if Neon Bindings are used instead of Tauri
- To improve function calls, we continue to experiment with different models and prompts. Currently using llama3 and the results are satisfactory. Also OllamaChat in LangChain doesn't support custom tool calling for agents, making it difficult to integrate the above features. See [#9917](https://github.com/langchain-ai/langchain/issues/9917), [#39](https://github.com/ollama/ollama-python/issues/39) and other issues in related repo
- Since Tauri usually doesn't support NextJS API routes (this is needed for ai.js), we share code and logic between NextJS API routes and a local server used in the Tauri app. To achieve this, the pkg package is used to package up a node server as a binary. This binary is then used as a sidecar in the Tauri app. However, this adds the problem of calling rust functions from the sidecar side. The solution is to spawn a server inside the Tauri app and let sidecar do http requests against that server which in turn calls the Tauri commands

### CODE REVIEW

**Comment by ArtemUpnode** [comment]
@betterbrand, resubmitted https://github.com/MorpheusAIs/Docs/pull/233

**Comment by greentea5435** [comment]
this work feels disconnected from https://github.com/MorpheusAIs/moragents, is this supposed to merge with that work later?

**Comment by ArtemUpnode** [comment]
> this work feels disconnected from https://github.com/MorpheusAIs/moragents, is this supposed to merge with that work later?

Morpheus agents don't necessarily have to be within one single client and technology stack, that's the philosophy behind Morpheus. It's a separate development based on Tauri and NextJs. Moreover, HSM Agents involve direct connection to devices using Rust backend. However, integration with moragents may be considered in the future, as it's also under development.

**Comment by greentea5435** [comment]
makes sense. it feels there are two different philosophies: 1. morpheus agents dont have to be a single client/tech stack, but 2. work must fall under a maintainer. does this mean that the maintainer must approve the different tech stack, which conflicts with the work the maintainer themselves are doing? additionally, how will the maintainer know how many weights the work is worth if the work is on a separate track? cc @LachsBagel [the maintainer] and @DavidAJohnston

**Comment by ArtemUpnode** [comment]
> makes sense. it feels there are two different philosophies: 1. morpheus agents dont have to be a single client/tech stack, but 2. work must fall under a maintainer. does this mean that the maintainer must approve the different tech stack, which conflicts with the work the maintainer themselves are doing? additionally, how will the maintainer know how many weights the work is worth if the work is on a separate track? cc @LachsBagel [the maintainer] and @DavidAJohnston
> 
> One counterargument with having a separate track of work is development is hard to track because it is not formally under a maintainer. an example is
> 
> https://github.com/MorpheusAIs/Docs/blob/cc654151098cb87c37dbd133cad87c5c2ded168d/Contributions/Code%20-%20Proof_Of_ContributionSnapshot3.md?plain=1#L127
> 
> , where a user was awarded weights for a tiny agent outside of the maintainer's track of work and hasnt worked on it for two months (https://github.com/JasonFengGit/MOR-Agent).
> I do agree with you on the philosophy of different technology stacks though, and I think this work looks promising - is this where an MRC is required i.e. submit an MRC and get community approval, then implement, especially for a project of this size?

I'm also discussing the development of this project with the maintainer. Maintainers can check different types of contributions from developers, and if they think the requested weights are correct, accept them, otherwise ask to lower them. And yes, big projects are best discussed with the maintainers first.

The weights for the agent you mentioned were for snapshot 3, when the implied value of weight was different. If this contribution was approved, it means it was reviewed and accepted by the maintainer. Moreover this agent is now being used in moragents.

As for MRC, we think that for this contribution, it may be redundant, but as development becomes more complex in the future (more agents and integration), it can be opened too.

**Comment by greentea5435** [comment]
Small correction that the agent/contribution I've linked is not being used in moragents. The agent currently being used is built by @cliffordattractor, and the contribution that I linked is a fork of that agent plus some additional small functionality which actually does not work [I've tried running both agents locally]. 

Otherwise, sounds good and agree on the thoughts around maintainer/contributor development relationships. Very interesting to see the project unfold, thanks for the discussion and for your contributions to Morpheus

**Comment by ArtemUpnode** [comment]
@LachsBagel

**Comment by LachsBagel** [comment]
This is disconnected

See this doc https://github.com/MorpheusAIs/moragents/blob/main/AGENTABILITIES.md#how-to-contribute

Thank you and hopefully we can find another way to merge in contributions based on the above

Appreciate your patience and time

**Pull request closed without merging**
