### PR TITLE
Update Code - Proof_Of_ContributionSnapshot5.md

### PR DESCRIPTION
**Pull request by openempires**
Elaboration of the MRC36. 
Processing of the feedback received.	
Assistance in 5 cases of weights discrepancy and hack. 
Implied weight value calculation and future system.

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
Thanks for the contributions.
Seems very high for an MRC not yet merged.
Also if the cost of doing weights checks exceeds the entire value of the weights in discussion it isn't efficient.
Let me know if you can come back with a smaller request.

**Comment by openempires** [comment]
Thanks for the review David.

I have adjusted the weights to a value comparable to that requested by other MRCs submitted in the past before being merged.

It is worth noting that MRC 36 is the second most commented MRC. There are still outstanding issues that I have not been able to address due to time constraints.

I have also halved the weights requested by weight revisions. Just a note, my revisions have identified about 900k recoverable weights. The application is still efficient. On the other hand, responding to requests may not always have a direct return in terms of weights but it does have a direct return in terms of community satisfaction.

**Comment by DavidAJohnston** [comment]
Thanks for the quick reply.

1. Glad to see the engagement. But a long post with lots of comments, replies and opinions is not the same as value accepted or delivered to the community. Otherwise the project will find it self with many lengthy discussions of things that can't be implemented or everyone giving their opinion to receive rewards. 

2. While the analysis proposed that high number of deprecations, further analysis found most of the contributions in question were maintained and thus only a small number were removed and even those now the authors are claiming the were, would have or meant to maintain them. Which created this further work.

This whole process should and must more toward automation as the manual version will not scale.
I'll post a entry for some weights, but most of the weights for MRC36 will need to come when its finalized and delivered.

**Comment by openempires** [comment]
David, I have read your comments about my PR to Snapshot 5 and I understand your point of view.

However, it is dangerous to use the ambiguity of ‘value delivered’ to the detriment of a contribution made. 

Objectively, I can quote you at least 4 MRCs who in the past have asked for a very similar value of around 75,000 USD for the work done in submitting it. We can accept that each MRC is unique and has different values but to give my MRC 10% of the value of others is a comparative tort that I find hard to understand.

I agree that any opinion should not be enough to be considered a contribution but I must remind you that you encouraged me to write this MRC and I understand that my draft MRC was reviewed and published as relevant content. And the 75+ comments of interesting debate and the 2 counter-proposals I think reflect that it is a topic of interest and can bring value to Morpheus.

To consider all this work worth 6500 weights is, with all due respect, ridiculous and offensive. Even more so when in the past we have seen more banal contributions with much higher values.

If these are the expectations, I am seriously concerned. What should I expect going forward? Could you give me concrete details? This uncertainty hardly encourages anyone to contribute.

My enthusiasm and values aligned with the project encouraged me to get involved. But maybe I was wrong after all.

**Pull request closed without merging**
