### PR TITLE
Update Code - Proof_Of_ContributionSnapshot4.md

### PR DESCRIPTION
**Pull request by polupoker**
- Made Discord bot responses private (visible only by users who trigger command) for better privacy of /stats command and less spam from users
- Moved to better VPS since Discord bot released to public and previous one suffered a bit because of inflow of requests.
- Revamped response to /links and /contracts commands
- Added hints for better usability of bot in Discord
- Added /launch command
- Minor cosmetic changes

### CODE REVIEW

**Review by betterbrand — CHANGES_REQUESTED** [review]
Docs 2024-04-30 17-54-15

Please include the MRI as explained at the top of the [contributions page](https://github.com/MorpheusAIs/Docs/blob/main/Contributions/Code%20-%20Proof_Of_ContributionSnapshot4.md#code-provider---proof-of-contribution-table-snapshot). 

There is a section that explains how and why there is new a new MRI column added to the snapshot this month.

**Comment by polupoker** [comment]
> Docs 2024-04-30 17-54-15
> 
> Please include the MRI as explained at the top of the [contributions page](https://github.com/MorpheusAIs/Docs/blob/main/Contributions/Code%20-%20Proof_Of_ContributionSnapshot4.md#code-provider---proof-of-contribution-table-snapshot).
> 
> There is a section that explains how and why there is new a new MRI column added to the snapshot this month.

Added MRI

**Comment by betterbrand** [comment]
Please change to mri 9 and we are good to go. We are making this process easier.

**Comment by polupoker** [comment]
Done!

**Comment by polupoker** [comment]
> Please change to mri 9 and we are good to go. We are making this process easier.

Done! Sorry for wrong MRI

**Review by betterbrand — APPROVED** [review]

**Pull request merged**
