### PR TITLE
Updated FAQ + MOR Claim Testing Guide + Contributions (MRI 1, 8, 9)

### PR DESCRIPTION
**Pull request by antonbosss**

### CODE REVIEW

**Comment by openempires** [comment]
Although the contributions are tremendously useful and of a high quality, 209,000 weights seems too much, considering that a complex contribution to the project such as https://github.com/MorpheusAIs/Morpheus-Lumerin-Node/tree/main/proxy-router has asked for 200,000.

Considering the value per weight of the previous snapshot, you would be claiming a contribution valued at $85,000 for tasks completed within 3 weeks.

Please reconsider your request.

**Comment by antonbosss** [comment]
Thanks for your suggestion!

**Comment by openempires** [comment]
I appreciate the review but you are still claiming 195,000 weights. Assuming that in these 3 weeks you have spent 12 hours of your time for 6 days a week, you are asking for an hourly rate of $370. 

Does it seem reasonable to you to ask for such a value for moderation tasks, updating documents and writing guides?

All this is not to question your commitment and the quality of your work, which are excellent. Only the requests seem a bit greedy.

**Comment by antonbosss** [comment]
Thanks for your comments and personal opinion, even though your calculations are out of context.

**Comment by openempires** [comment]
If you like, we can agree on an approximate hourly rate and apply it to both of us, what do you think?

If you think my statements are out of context, please clarify.

My "8 messages" total 11,000 words, they required prior study and research as you can see from the data presented. It was more like 2-3 hours of dedication for each message.

First of all, I want to be objective and I apologise if I offended you, but I think many members of the community might be surprised to see these figures in this time period and for these jobs.

**Comment by antonbosss** [comment]
Again, thank you for you close attention to my submission, but I don't feel that I should discuss my contributions with anyone other than the maintainers.

**Comment by openempires** [comment]
In the event that all your contributions are not public and accessible, I suggest that it would be good practice to add them as comments and explain them if a member of the community is interested in them.

No doubt the maintainers have the final say, but the community also has the right to ask questions. You can not answer if you don't want to, but not justifying such a high value figure and being a highly visible contributor to Morpheus damages the image of the project.

If a maintainer would accept something like that, it would be corroborating a bad practice that does not advocate transparency.

**Comment by openempires** [comment]
You still don't answer and you seem to get angry when I try to have an objective conversation.

I already gave you clear explanations about the value of my contribution. You did not. This is not a personal attack, but your answers are evasive and not very concrete. Claiming that you are able to contribute $80,000 worth of value in 3 weeks deserves an explanation. It's a significant amount, really. There are people who work 3 years to get that amount.

I have the guide present. There is no way to properly value a contribution. Everyone's assessment is purely subjective and if something seems out of line, everyone is entitled to give their opinion and ask for clarification.

I would like to know why you consider that you have contributed $80,000 of value and not $20,000 or $250,000.

**Comment by antonbosss** [comment]
I don't have a bad habit of valuing other people's contributions and I'm not envious.  

I don’t plan to discuss anything with you, much less give any explanations, because I shouldn’t do that.

Please reflect on your toxic unacceptable behavior.

**Comment by openempires** [comment]
Well, it's clear to me that you're not going to respond.

In a project that aspires to be built collaboratively, you ask for attention-grabbing amounts and then don't explain. You also choose to attack me. 

Honestly, I don't know what behaviour is more toxic and unacceptable for the good of the community. The one who asks for more info or the one who refuses to answer and discredits.

I want to believe that this is an isolated case within Morhpeus. The way the maintainer acts will be decisive in this case to see if the problem spreads.

Thank you in any case for your answers.

**Comment by antonbosss** [comment]
Here's the translation into English:

Just another juggling of words. 
I think it's necessary to put everything in its place. 

Firstly, all the information is available in a table for everyone; it is open and transparent. 

Secondly, only the maintainers of the repositories can assess the contribution, as they see the process from the inside. 

Thirdly, I am ready to explain and argue how my contribution will bring much greater benefit than the amount I requested as weight, and also to adjust it if the maintainers consider it necessary. 

Fourthly, when people ask, rather than hide personal attacks behind their questions, they do not use a passive-aggressive tone and listen to the arguments and facts presented to them. 

Fifthly, it is your personal fiction that any of the contributors owe you an explanation regarding their contribution. But if you ask in proper way, they will.

Sixthly, you lack the qualifications and information to assess anyone. Additionally, as a contributor, you are subject to cognitive biases like self-enhancement bias and effort justification bias. 

And finally, nothing stops you to do better and for less weight, so your contribution is chosen. 
You can even fork and make your own Morpheus where people will provide you personal extended report with dances and black jack.

Instead you did nothing than this drama in GitHub comments.

Have I made myself clear?

**Comment by openempires** [comment]
It is worrying that a contributor of your stature and visibility should express himself in this way.

At all times I have kindly asked you to help me understand how such a contribution is justified. But you have taken it as a personal attack. 

You still haven't given an answer to my question. Morpheus is as much yours as it is mine as it is of any other contributor's.

Why should I abandon the project because 1 contributor is asking for a high value and is not giving explanations? I don't understand the logic.

**Pull request merged**
