### PR TITLE
Update Code - Proof_Of_ContributionSnapshot4.md

### PR DESCRIPTION
**Pull request by Potentiated**
Administration of Socials, Design elements, infographics, Integrations, CG and CMC listings, testing Uniswap integration, dashboard and wallet.

Anon Contributions on Design and Listing support

### CODE REVIEW

**Comment by ArtemUpnode** [comment]
There is no "Link to Work" for the first contribution. For PR https://github.com/MorpheusAIs/Docs/pull/238, there is already a contribution from a contributor (https://github.com/MorpheusAIs/Docs/pull/240). Other links are incorrect (404 page).

There are also formatting issues (e.g. missing spaces).

**Comment by openempires** [comment]
Thank you very much for your contribution and that of the anonymous people you represent.

In the absence of proof of contribution, could you please detail what the contributions consist of?

For the description given and the time period, it seems too much the weights requested considering that 100,000 weights would be $41,000 in snapshot 3.

It also seems too much 20,000 weights ($8,000) and 25,000 pesos ($10,000) for logo design and infographics.

Could you explain how you have concluded that this is the value provided for these tasks?

Thank you in advance.

**Comment by Potentiated** [comment]
These are tasks that have been ongoing and reflected in the previous repositories and documentation. The first contribution mentioned in PR #238 is joint contributions, we have been working on integrations for Morpheus since month 1, reflected in what is mentioned in the PR and more, with some strong collaborators integrated this month, including various smart agent projects contributing and getting them onboarded. As for the Designs the links is currently broken but you can go into Docs, Assets to and the link there to see what work has been concluded. 

I think denomination of work done to the Nth degree here and calculating to the last dollar is honestly bad form. I think it goes against the spirit of the Value of Labour Theory and is ultimately demotivating and demoralizing when it comes to contributing to the project. I have been contributing from the beginning and the work concluded has been been equal to what has been done in previous months, honestly more in this case with regards to some of the contributions, and I have been adjusting to the current calculations.

I have concluded the value from what it brings to the project, which is hard to quantify in regards to some of these elements of the project, even harder when it is typically developers that scrutinises it, but I attest to their being value, and so do the people that are implementing these integrations, designs, etc.

**Comment by openempires** [comment]
Thank you very much for your reply giving more details on the contributions and for your contributions on the integrations.

I am familiar with the Labor Theory of Value. My question is more about how this value has been determined. I am hoping to come up with a pattern that can be useful to the community as currently there are many doubts about how to determine it and it is extremely subjective.

I am sorry that my questions may discourage you. That is not the purpose at all. I think it is reasonable to do some monitoring to ensure that contributions are fair.

For example, on PR #238 , the contributor is already asking for another 136,000 weights and the list of contributions is very ambiguous. Also, from what @LachsBagel  comments, it seems to be unrepresentative. I have had the opportunity to talk to another project on the list and they have told me that, apart from one conversation, there has been no further progress yet.

If that is the case, perhaps it would be appropriate to adjust the weights in the 2 PRs to a reasonably explainable value.

**Comment by betterbrand** [comment]
Weights adjusted.  Please resubmit PR based on amount noted in smart contract.  Moving forward, pull requests not approved by the last day of the month, will not be adjusted, but will be rejected and not considered until the following month.

**Pull request closed without merging**
