### PR TITLE
Video Marketing Content

### PR DESCRIPTION
**Pull request by anggagilang11**
Video marketing content, requested by The Oracle
https://drive.google.com/drive/folders/1y97hLKOFZ48xwljuvDQsdjYA6Pw_f1Un?usp=drive_link

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
Thanks for the contribution. Not really any "marketing" for Morpheus as its a community project.
I'll ask for more details on the educational utility and technical nature of these contributions.

**Comment by anggagilang11** [comment]
There is a video for the needs of Decentralized AI Day at ETH Denver. I also added several public & private APIs from crypto exchanges in Indonesia.

image
image
image
image

**Comment by DavidAJohnston** [comment]
What is the context of the APIs?
The MOR tokens don't trade yet.
Is this the context of guiding people where to get stETH?

**Comment by anggagilang11** [comment]
In addition to getting crypto price feeds for future development

**Comment by DavidAJohnston** [comment]
Still conflicts. And its nice you talked with Oracle. Though he is not a maintainer of this Github repo. He is a community member. There isn't generally rewards for video stuff. Some educational hours have been credited, but seems like enough of that has been done already. The rewards here are for Code and the rewards for "Community" are for Frontend Developers and those rewards aren't live until Phase 3.

**Pull request closed without merging**
