### PR TITLE
Update Code - Proof_Of_ContributionSnapshot3.md

### PR DESCRIPTION
**Pull request by Suko**

### CODE REVIEW

**Comment by quertc** [comment]
As far as I know, fractions are not supported (`0.2`).

**Comment by Suko** [comment]
Ok fixed, tnx!

**Comment by DavidAJohnston** [comment]
@quertc is correct fractions are not supported. However the weights are being multiplied by 2,000 X this snap shot as part of the MOR Weights Rebase MRC so I'll update the weights then. https://github.com/MorpheusAIs/MRC/blob/main/Accepted/MRC14.md

**Comment by quertc** [comment]
Btw, those PRs were not merged. Probably need to cancel the weights?

**Pull request merged**
