### PR TITLE
Update Code - Proof_Of_ContributionSnapshot5.md

### PR DESCRIPTION
**Pull request by rethereum1**

### CODE REVIEW

**Comment by rethereum1** [comment]
Creation of a complete MOR ERC20 token dashboard. 

The dashboard connects directly to the blockchain and pulls information on: 

- MOR Transfers
- MOR claimed
- MOR token accumulation
- The liquidity orderbook of all MOR univ2 & uniV3 LPs
-  Detailed breakdown of each LP holder, position and the fees earned
- MOR live trade tracker, trades by size & price in ETH and USD
- MOR token holders treemap & list 


Dashboard here: [https://parsec.fi/layout/BT/brknrAI5](https://parsec.fi/layout/BT/brknrAI5)

**Comment by betterbrand** [comment]
For this amount of weights, please include a detailed explanation guide to each element in the dashboard.  Explain all financial terms.  Ask others on discord for help if needed.

**Comment by rethereum1** [comment]
okay @betterbrand i will include this guide

**Comment by rethereum1** [comment]
@betterbrand i included a full guide in my proof of contribution:

the full guide is here: https://docs.google.com/document/d/1f3g_qZ51ogWxOqrH9gkPdkXVFSMeX54SNyReT-Ca5jw/edit

**Pull request closed without merging**
