### PR TITLE
Translated whitepaper and yellowpaper to Traditional Chinese

### PR DESCRIPTION
**Pull request by JasonFengGit**
Traditional characters are commonly used in Taiwan, Hong Kong, and Macau, as well as in most overseas Chinese communities outside of Southeast Asia.

### CODE REVIEW

**Comment by JasonFengGit** [comment]
Updated README.md with valid papers links after reorg.

https://github.com/MorpheusAIs/Morpheus/pull/652

**Comment by DavidAJohnston** [comment]
Thanks. There is a conflict with the merge.
Also 20 hours is a lot considering the implied value of weights is more than $400 USD per weight right now. 
You are requesting $8,000 USD worth of weights. And the Yellow Paper isn't even ready for translation.
If you update the weight to 1 and offer the white paper I'll merge that. Or you can close the PR. Thanks.

**Comment by JasonFengGit** [comment]
Hi @DavidAJohnston , thank you so much for the reply! I updated to PR for only the Whitepaper and change the hours to 2, which I think is reasonable. Thanks!

**Comment by DavidAJohnston** [comment]
Again. Its weights not hours. But yes 2 is reasonable. Thank you. Merging.

**Comment by JasonFengGit** [comment]
Thx!

**Pull request merged**
