### PR TITLE
Fix proof of contribution snapshot 1 - 4 tables

### PR DESCRIPTION
**Pull request by mor-codes**
Fix proof of contribution snapshot 1 - 4 tables in a perfect format!

This is required for external application such as mor.codes to parse the contribution table.

### CODE REVIEW

**Comment by mor-codes** [comment]
A message from Dorian in discord

> thanks for updating the table but I still don't see my contribution from snapshot 3 which has been mistakenly removed on May 8th?
> 
> https://github.com/MorpheusAIs/Docs/pull/148/commits/fee6f46fac24c9f01f116403b64ec9dcfc65556c

**Comment by mor-codes** [comment]
We have discovered one record without an MRI in snapshot 2 for wallet address 0x8b194B58B47ff0008ac89a99e54cFdB3ca2f4a5F about translating Whitepaper to Vietnamese.

**Comment by betterbrand** [comment]
the files seem to be conflicting.  Please fix

**Comment by mor-codes** [comment]
Should be fixed by changing 0xe70Ac2bAFdcD047B34dfB4B056bFDb941b91b0c9 to 0x4317C2A305857eD8A9Bc2Db3190083584C916bd2

**Comment by DavidAJohnston** [comment]
Rather then change the source file. I'd recommend forking it and making this change on your own repo.

**Pull request closed without merging**
