### PR TITLE
Add morcodes weight cross-check and snapshot table fixing contribution for snapshot 5

### PR DESCRIPTION
**Pull request by mor-codes**
Here are our contributions:
- [x] Fix broken snapshot 1-4 tables (https://github.com/MorpheusAIs/Docs/pull/269)
- [x] Publish normalized CSV files for data analyst to analyze the weight data easily (https://github.com/mor-codes/Morpheus-Code-Contribution-CSV)
- [x] Incorporate new snapshot data with MRI to https://mor.codes
- [x] Cross-check with the original version of the snapshot table to hunt for missing weight records

Note: A report was received about a missing weight record (missing before our fix). We will cross-check with the original version of the snapshot table.

We also discovered one record without an MRI in snapshot 2 for wallet address 0x8b194B58B47ff0008ac89a99e54cFdB3ca2f4a5F about translating Whitepaper to Vietnamese.

Fixing the broken snapshot tables required considerable effort due to numerous corner cases and corrupted records that needed manual corrections.

Having a broken snapshot and an unstable table structure is obviously a blocker for the fully functional development of mor.codes!

We believe that fixing the snapshot tables and identifying missing records will have a significant impact on Morpheus. This effort also opens up opportunities for future analytics on code contribution weight to determine the best weight allocation guidelines.

**Identifying a 2.7M weights printed due to error should worth 50k weight. These weights can be allocated to new contributors for months**

### CODE REVIEW

**Comment by mor-codes** [comment]
Here is the weight comparison, cross-checked with the original version of the snapshot table, to identify missing weight records. This data was parsed using both automated tools and manual filtering, then categorized into Missing and Printed categories.

https://docs.google.com/spreadsheets/d/14VeA4fOqBGIjFynrLYeOhVdKaFGdb1Frtp2ltOIuNm4/edit?usp=sharing

image

Source code: https://colab.research.google.com/drive/1OJrzOtF8Jg8OLee03NJH63pj_xowS7M6?usp=sharing

Raw output: [weight_comparison.csv](https://github.com/user-attachments/files/15512143/weight_comparison.csv)

## Highlights

* A total of 10,453,581 weights are MISSING from 56 wallets.
* A total of 12,536,920 weights are PRINTED out of thin air to 47 wallets.

These discrepancies highlight the inaccuracy and transparency issues of the new contribution data. For instance, one such issue was reported in Discord but went unacknowledged.

image

**Comment by mor-codes** [comment]
For the most added weight (2.7M weight) it's a single entry without explaination of DecentralizeAI/MRC

image

Below screenshot show that this 2.7M weight actually exists

image

0xfe17147301888fBEEc36be3a8e6E4f883496ed33 with 660 original weight do get weight reduction but it can't be as much as 2.7M weight

It appear to be a rounding error (It have been multiplied by 10, it should be ~0.27M)

**Comment by mor-codes** [comment]
Weight for https://github.com/DecentralizeAI/MRC related contributions

* **[Original](https://raw.githubusercontent.com/MorpheusAIs/Docs/8b23b6722932ff0b5b69566745fc5745f26cb821/Contributions/Code%20-%20Proof_Of_Contribution.md)**: 1,110 * 2,000 = 2,220,000
* **[New](https://raw.githubusercontent.com/MorpheusAIs/Docs/4597e3e8ed9a2be1fa1d3c479bee3373e5a96b50/Contributions/Code%20-%20Proof_Of_ContributionSnapshot1.md)**: 4,493,120
* **Difference**: -2,273,120

Without this extra 2.7M weight, new weight will be reduced to 4,493,120 - 2,747,680 = 1,745,440, resulting in a -474,560 weight different

**Comment by betterbrand** [comment]
I appreciate you've spent time on this but there isn't 50000 weights budgeted in MRI 8 for this snapshot.  Where was the request for this accounting and what was the result?

**Comment by betterbrand** [comment]
You received weights for mor.codes in the last snapshot, new weights aren't given for maintenance.  Pleas fix this and address the questions above.

**Comment by mor-codes** [comment]
Reduced to 20000 weights, removed mor.codes and break down to two contributions

* 10000 weights - Fix the broken snapshot 1-4 tables and publish normalized CSV files for the data analyst to analyze the weight data easily - https://github.com/MorpheusAIs/Docs/pull/269
* 10000 weights - Cross-check the original version of the snapshot table to hunt for missing and additional weight records, detecting an additional 2,083,339 weights added to the new snapshot files

For cross-checking with the original version of snapshot you can see above for the result
* A total of 10,453,581 weights are missed from 56 wallets.
* A total of 12,536,920 weights are added to 47 wallets.
* Additional 2,083,339 (12,536,920 - 10,453,581) is being added in new snapshot files

One obvious case is a 2.7M weight highlighted above, which is a significant amount and only exists in the new snapshot file. Since this case isn't resolved yet, the weight for this case can be moved to the next snapshot.

Would you like me to continue checking all missing and added weights in the upcoming snapshot?

**Comment by DavidAJohnston** [comment]
Already have been many reviews and audits of the contributions.
The observations above are incorrect and inaccurate as they lack the context of the contributions.

Due to Anon contributions there isn't a perfect tic and tie for everything and there won't be. So its not a valuable use of time to continue this analysis.

These weights requests are very high. Closing this PR.

**Comment by mor-codes** [comment]
But your auditor not even noticed this case reported on the Discord

image

**Pull request closed without merging**
