### PR TITLE
Update Code - Proof_Of_ContributionSnapshot5.md

### PR DESCRIPTION
**Pull request by framedintent**
https://github.com/framedintent/MorphyLLM

### CODE REVIEW

**Comment by greentea5435** [comment]
confused how this work ties in with https://github.com/MorpheusAIs/moragents? the repo linked just has a couple of images and imports an existing model

**Comment by framedintent** [comment]
> confused how this work ties in with https://github.com/MorpheusAIs/moragents? the repo linked just has a couple of images and imports an existing model

This is the training code for a new model based on Mistral Instruct v0.3, which will be applied in the future for agents. Please read the readme. Thanks!

**Comment by framedintent** [comment]
@rcondron @DavidAJohnston Can I ask for a review, please?

**Comment by DavidAJohnston** [comment]
This seems a future development. Please re submit then. MRI is maintained by @LachsBagel

**Pull request closed without merging**
