### PR TITLE
Update Morpheus Logo - White.svg

### PR DESCRIPTION
**Pull request by iguanarchist**
Revised to an actual vector format. Prior file was a masked bitmap, not true vector.

I have no clue what MRI such changes fall under, and I'm sure I read somewhere that minor edits/additions don't need to declare a MRI or weights. If I'm incorrect, please direct me to the proper documentation for procedure.

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
Thanks. Seems to be conflicts with the PR. Happy to merge.

**Comment by DavidAJohnston** [comment]
@iguanarchist still a conflict in the pull request.

**Comment by iguanarchist** [comment]
It achieves the same thing as the other request that was already committed,
this one can be ignored.

**Comment by DavidAJohnston** [comment]
Ok. Thanks.

**Pull request closed without merging**
