### PR TITLE
added snapshot 6 readme for june to july

### PR DESCRIPTION
**Pull request by dannweeeee**
Created Snapshot 6 for Code Contributors.
MRI Number 8. Code Proofs & Dashboards

### CODE REVIEW

**Comment by dannweeeee** [comment]
tagging @antonbosss @betterbrand @DavidAJohnston

**Review by DavidAJohnston — APPROVED** [review]
Looks good. Thanks.

**Comment by betterbrand** [comment]
Why is this allocated to 8?

**Comment by dannweeeee** [comment]
i have updated from 8 to 3! apologies for the mistake @betterbrand 

here is the new PR https://github.com/MorpheusAIs/Docs/pull/343

**Pull request merged**
