### PR TITLE
Update Yellowstone Compute Model

### PR DESCRIPTION
**Pull request by Oktaivan**
Updating text in main Yellowstone Compute Model (English) and international version to match current WP, updating links to KEYDOCS.

### CODE REVIEW

**Comment by antonbosss** [comment]
@Oktaivan Hi. Can I ask you for a reason you decided to replace Compute Providers / Compute to Community builders / Community in the Yellowstone Compute model?

**Comment by Oktaivan** [comment]
> @Oktaivan Hi. Can I ask you for a reason you decided to replace Compute Providers / Compute to Community builders / Community in the Yellowstone Compute model?

Hi, Anton! Good to see you! I've replaced this according to the latest version of WP, that's how the Yellowstone Compute model document goes about quoting the outdated "Compute Proof, Registration & Reward" chapter, which is now called "Community Builder Proof, Registration & Reward". In the latest version of WP Compute Provider has been replaced by Community Builder.

**Comment by antonbosss** [comment]
Thanks for your

> Hi, Anton! Good to see you! I've replaced this according to the latest version of WP, that's how the Yellowstone Compute model document goes about quoting the outdated "Compute Proof, Registration & Reward" chapter, which is now called "Community Builder Proof, Registration & Reward". In the latest version of WP Compute Provider has been replaced by Community Builder.

Thanks for your reply. There might be some confusion as I've just checked and WP includes both sections Compute and Community and seems nothing was replaced.
ice_screenshot_20240303-195043
ice_screenshot_20240303-195051

**Comment by Oktaivan** [comment]
> Thanks for your
> 
> > Hi, Anton! Good to see you! I've replaced this according to the latest version of WP, that's how the Yellowstone Compute model document goes about quoting the outdated "Compute Proof, Registration & Reward" chapter, which is now called "Community Builder Proof, Registration & Reward". In the latest version of WP Compute Provider has been replaced by Community Builder.
> 
> Thanks for your reply. There might be some confusion as I've just checked and WP includes both sections Compute and Community and seems nothing was replaced. ice_screenshot_20240303-195043 ice_screenshot_20240303-195051
Hm. The current Yellowstone Compute Model document quotes the lines (From the original white paper):

“The pro-rata MOR transaction fees burned by each Compute Provider serves as proof of the Compute Providers status and earns a proportion of the MOR tokens each day.`

`For example, if there are 100 Compute Providers on day 1 when the network launches, then each one gets a pro-rata reward based on the amount of MOR they have burned via fees. In this case, presuming each of the 100 compute providers burned 100 MOR, then 1% of the 3,456 MOR tokens each day = 34.56 MOR.”

In the current WP these words no longer exist. You should also take into account that these are lines from the chapter “Community Builder Proof, Registration & Reward”, so I changed the title of this chapter in my commit. This seems logical to me.
Yellowstone

**Comment by antonbosss** [comment]
I believe that you know that Community and Compute Providers these are two different groups of contributors, therefore
Whitepaper has two distinct sections describing them.
Compute section has been recently updated with information from the Yellowstone Compute model paper as this model was adopted. 
Compute Providers can't be replaced by Community Providers the same as Capital Providers can't be replaced by Code Providers as this is totally confusing.

**Comment by Oktaivan** [comment]
> I believe that you know that Community and Compute Providers these are two different groups of contributors, therefore Whitepaper has two distinct sections describing them. Compute section has been recently updated with information from the Yellowstone Compute model paper as this model was adopted. Compute Providers can't be replaced by Community Providers the same as Capital Providers can't be replaced by Code Providers as this is totally confusing.

Yes, Anton, I understood what you mean, you’re really right!) Thank you! I'll close this pool request and edit my commits. However, I think the Yellowstone Compute Model document needs to be edited in the sense that this model has already been accepted and taken into account in the latest version of WP, so it will be more logical.

**Comment by antonbosss** [comment]
I would be happy to discuss with you changes you think is needed in discord or telegram

**Pull request closed without merging**
