### PR TITLE
Update YellowPaper

### PR DESCRIPTION
**Pull request by Oktaivan**
Correction link on WP and minor inaccuracies (commas, etc.); update the link to the actual WP in International YellowPaper.
Upd. I apologize, I couldn't figure out if the document needed a link to the actual WP or if you wanted to leave a link to the original document from the "SmartAgentProtocol" repository. If this is the case, please close my request.

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
Conflict in Yellow Paper Ukrainian. Please review.

**Comment by DavidAJohnston** [comment]
Conflicts with the Ukrainian paper.

**Comment by DavidAJohnston** [comment]
Lot of conflicts. Likely due to over Pull Requests by Anton to update these.

**Comment by Oktaivan** [comment]
Ok, most of my commits got in conflict due to file location change, will have to do it all over again.

**Pull request closed without merging**
