### PR TITLE
Update Code - Proof_Of_ContributionSnapshot4.md

### PR DESCRIPTION
**Pull request by luvsourcandy**
https://github.com/MorpheusAIs/Docs/assets/155991151/966ce56b-ce0c-4dd9-83a2-fdf23ec3a201

### CODE REVIEW

**Comment by luvsourcandy** [comment]
not sure if you guys want to apply this to Morpheus discord avatar's server.

think we should change something news to celebrate upcoming launch of Morpheus

**Comment by antonbosss** [comment]
Interesting suggestion. Can you make the same, but with reversed colors and purple Morpheus color for background and green logo?

**Comment by luvsourcandy** [comment]
> Interesting suggestion. Can you make the same, but with reversed colors and purple Morpheus color for background and green logo?

Of course ! 
Just to be sure . It will be 2 version : 
1. Green background + white logo
2. Purple background + green logo

Right ?

**Comment by antonbosss** [comment]
Yes, that would be awesome to have.

**Comment by luvsourcandy** [comment]
https://github.com/MorpheusAIs/Docs/assets/155991151/4beee3f1-9c59-410a-b2ad-41d2898152cb

https://github.com/MorpheusAIs/Docs/assets/155991151/60e40f8f-8649-4318-b7bd-b8e170a137d1

here 2 preview , check it out.

i updated raw files into google drive link.

**Comment by antonbosss** [comment]
It looks good!

**Comment by antonbosss** [comment]
Can you please message me in Discord: antonb?

**Comment by luvsourcandy** [comment]
> Can you please message me in Discord: antonb?

Sure! Will pm you, my discord id is luvsourcandy too

**Review by betterbrand — APPROVED** [review]

**Comment by betterbrand** [comment]
merged in a previous pr

**Pull request closed without merging**
