### PR TITLE
Update Code - Proof_Of_ContributionSnapshot8.md

### PR DESCRIPTION
**Pull request by asxnlabs**
# Added: Morpheus AI Metrics Dashboard

- Developed Morpheus AI Metrics Dashboard
- Integrated supply and staking pages. 
- End-to-end Frontend & Backend Development + API Code. 
- Gitbook Catalog created which includes FE and BE examples along with the API reference including all endpoint specs and examples. 
- [Morpheus AI Metrics Dashboard Code PR](https://github.com/MorpheusAIs/stats-graphs-and-endpoints/pull/1)
- [Morpheus AI Metrics Dashboard Hosted Webapp](https://mor-explorer-frontend.pages.dev/)
- [Morpheus AI Metrics Dashboard GitBook Catalog](https://nirmaans-organization.gitbook.io/morpheus-explorer)

### CODE REVIEW

**Comment by NirmaanAI** [comment]
Developed under the guidance of @betterbrand and @antonbosss

**Comment by DavidAJohnston** [comment]
@betterbrand For your review and approval.

**Comment by betterbrand** [comment]
@asxnlabs the merge was on another repo and your weights were assigned.  will conflicts noted above affect this?  Is this a rollup of deliverables?

**Comment by asxnlabs** [comment]
@betterbrand @DavidAJohnston This is an older request we opened a month back. 

Since then we have been closely working with @betterbrand and were assigned the weights for the contribution mentioned in this PR. The delivery has been completed for this PR and the weights have already been assigned, thus, we will be closing this pull request immediately. We apologize for any confusion caused.

**Pull request closed without merging**
